name: Build driver loader
on:
  push:
    branches:
      - master
    paths:
      - dockerfiles/drbd-driver-loader/*
      - .github/workflows/build-injector.yaml
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build images
        run: |
          cd dockerfiles/drbd-driver-loader
          make update
      - name: login to registry
        env:
          QUAYIO_USERNAME: ${{ secrets.QUAYIO_USERNAME }}
          QUAYIO_PASSWORD: ${{ secrets.QUAYIO_PASSWORD }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          docker login --username=${QUAYIO_USERNAME} --password-stdin quay.io <<< "${QUAYIO_PASSWORD}"
          docker login --username=${DOCKERHUB_USERNAME} --password-stdin docker.io <<< "${DOCKERHUB_PASSWORD}"
      - name: push images
        run: |
          cd dockerfiles/drbd-driver-loader
          make upload REGISTRY="quay.io/piraeusdatastore docker.io/piraeusdatastore"
